### ISSUE TITLE
failed to create ISO

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix-iso-builder#1]
trace observed:

<pre>
P: Begin building root filesystem image...
P: Preparing squashfs image...
P: This may take a while.
Parallel mksquashfs: Using 2 processors
Creating 4.0 filesystem on binary/casper/filesystem.squashfs, block size 1048576.
Killed
P: Begin unmounting filesystems...
P: Saving caches...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mount: binary.hybrid.iso: failed to setup loop device: No such file or directory
umount: /tmp/tmp.Bgyj3GfjwP/mnt: not mounted
Warning: creating filesystem that does not conform to ISO-9660.
genisoimage: Uh oh, I cant find the boot catalog directory 'isolinux'!
isohybrid: could not open file `binary.hybrid.iso': No such file or directory
md5sum: binary.hybrid.iso: No such file or directory
sha256sum: binary.hybrid.iso: No such file or directory
mv: cannot stat 'binary.hybrid.iso': No such file or directory
</pre>

**Comment by fossfreedom** [comment]
note - had a look at a previous run and I saw an ISO was created.

This commit 

 https://github.com/budgie-remix/budgie-remix-iso-builder/commit/76e299113449f17bc515df2abca07ca367eeced1

due to the error observed about isohybrid not being installed I installed that extra dependency.

Maybe that extra dependency is not needed and is the cause of the failure.  The script maybe incorrectly saying that isohybrid should be installed.  Need to investigate further.

**Comment by spottech** [comment]
Looking after the error in the log of your terminal
I see this in your comment 
-> Creating 4.0 filesystem on binary/casper/filesystem.squashfs, block size 1048576.
**Killed**

**Comment by fossfreedom** [comment]
yeah - I don't know why the process died.  I will restart the build again tonight and see if the same thing happens or if the ISO completes correctly.  Will let you know what happens.

**Comment by fossfreedom** [comment]
![](http://pix.toile-libre.org/upload/original/1460751957.png)

ok, my build machine was created as follows

virtualbox - latest amd64 mini.iso for xenial

installed no desktop environment i.e. just a simple text based install

installed git

git clone http://github.com/budgie-remix/budgie-remix-iso-builder

installed all the packages in the README - including syslinux-utils

run sudo ./terraform.sh

That's when I can the above error.

I'm going to try the following now:

sudo apt purge syslinux-utils

run sudo ./terraform.sh

will let you know what happens.

EDIT: same as above - same error and fails to create an ISO

EDIT: looks like missing python-minimal as a dependency

**Comment by fossfreedom** [comment]
ok - have now successfully created an ISO.

To close this issue we need to add the dependencies python-minimal and syslinux-utils

The terraform.sh script maybe should automatically install all dependencies.  This will prevent future issues.

**Comment by spottech** [comment]
Ok I'm close this issue, I'm an bug in start terraform.sh is'nt install missing package, fix with manually install it, i see this later isn't an very high importance
