### ISSUE TITLE
failed to load ldlinux.c32

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix-iso-builder#10]
![screenshot from 2016-04-19 20 18 44](https://cloud.githubusercontent.com/assets/996240/14652635/1058e8f8-066d-11e6-826b-b2909790dbf3.png)

latest git clone build produces the above on both 64bit and 32bit builds

**Comment by spottech** [comment]
I do not have this problem, check if everything is copy well during the build
boot fine in 32-64Bit and ufi and no ufi virtualbx

**Comment by fossfreedom** [comment]
possibly this is because I cloned the isobuilder project before you had finished making the latest changes to the syslinux project.  

I'll delete and set off another clone & build.
