### ISSUE TITLE
Critical: Check Installable on EFI laptops

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix-iso-builder#2]
While I haven't managed to generate an ISO yet, need to test the ISO on an EFI laptop / virtualbox with EFI set.

When working with Pinguy there are changes known in xenial that prevents EFI based installs.

probably here https://github.com/budgie-remix/budgie-remix-iso-builder/blob/bfb55e39b7b4197f7062a33fb4efcc7f882571f1/etc/config/package-lists/desktop.list.chroot_live

Pinguybuilder has this to help - mokutil and libefivar0 are key

<pre>
 if [ "$ARCH" = "amd64" ] ; then
    apt-get download b43-fwcutter bcmwl-kernel-source efibootmgr grub-common gru
b-efi grub-efi-amd64 grub-efi-amd64-bin grub-efi-amd64-signed grub-efi-ia32 grub
-efi-ia32-bin grub-pc-bin grub-pc grub2-common grub-gfxpayload-lists libefivar0 
mokutil secureboot-db shim shim-signed &> /dev/null
    else
    apt-get download b43-fwcutter bcmwl-kernel-source efibootmgr grub-common gru
b-efi grub-efi-ia32 grub-efi-ia32-bin grub-pc-bin grub-pc grub2-common grub-gfxp
ayload-lists libefivar0 mokutil secureboot-db &> /dev/null
    fi
</pre>

EDIT: probably needs to be added to etc/config/package-lists/pool.list.binary

**Comment by spottech** [comment]
I will test on my son's computer

**Comment by spottech** [comment]
It's boot great, but I have not had the opportunity to test the installation

**Comment by spottech** [comment]
Actually boot well on a uefi pc/laptop but not on ufi virtualbox

**Comment by fossfreedom** [comment]
Did you have secure boot enabled on the laptop?

**Comment by spottech** [comment]
in my desktop computer yes, i'm not an laptop with uefi

**Comment by fossfreedom** [comment]
@spottech - on my testing all looks ok - installs correctly on uefi and non-uefi.

**Comment by spottech** [comment]
Are you test thé boot after installation on uefi?

**Comment by fossfreedom** [comment]
yep - works for me.

**Comment by spottech** [comment]
OK fine
