### ISSUE TITLE
unnecessary dependency

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix-iso-builder#3]
doubtful that ubuntu-ubiquity-artwork is needed - need to check if can be removed. 

This will reduce the ISO size

https://github.com/budgie-remix/budgie-remix-iso-builder/blob/bfb55e39b7b4197f7062a33fb4efcc7f882571f1/etc/config/package-lists/desktop.list.chroot_live

**Comment by spottech** [comment]
ubuntu-ubiquity-artwork removed from list bust still present in dependency.
I closed this issue
