### ISSUE TITLE
set an image on grub

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix-iso-builder#4]
With PinguyBuilder grub has a 640x480 png set.

Can this ISO script do similar - or is there another way to do this?

Note - for the release candidate the 640x480.png image is going to be based upon the budgie-remix-plymouth theme background so that there is a seamless transition between grub to plymouth.

**Comment by spottech** [comment]
Hi, for set grub image maybe create an grub theme, I see if is possible without

**Comment by spottech** [comment]
I'm test to add the grub background basicly, I'll let you know.
The must have is an grub theme, see the grub theme of ubuntu mate as base?

**Comment by fossfreedom** [comment]
in terms of priorities - grub theme is NOT a priority.  It is a nice to have - i.e. it would be great to have it fixed but we can release 16.04 without a theme for grub.

The priority is the EFI installation.  We need to test both a 32bit and 64bit install - both on a standard laptop / standard virtual box VM and on a EFI based laptop / virtual box VM with EFI ticked.

**Comment by spottech** [comment]
For grub theme it's just an dream ;)
EFI installation test is my next step, now I see for the grub background and reduce iso size with remove no necessary dependency.

By cons I still have the bug with nm-applet.
The dialog box for the wifi password is not displayed.
The autostart file nm-applet should be in the home folder at start of session, I will open an issue in budgie-desktop

**Comment by fossfreedom** [comment]
check in /etc/xdg/autostart for the nm-applet autostart .desktop file

Only a user can add to their home folder i.e. ~/.config/autostart

**Comment by fossfreedom** [comment]
not needed anymore
