### ISSUE TITLE
live ISO does not autologin

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix-iso-builder#5]
don't know why - after creating an ISO successfully - on boot the ISO does not autologin.  

no idea what the user name and password is to login to the live ISO

**Comment by spottech** [comment]
I see,
the first iso i make have autologin... i see this

**Comment by fossfreedom** [comment]
ok have retried again this morning.

Have deleted 

sudo rm -rf budgie-remix-iso-builder

git clone this again

sudo su

./terraform.sh

The ISO generated does not autologin when booting up in virtualbox.

**Comment by spottech** [comment]
That is true
I worked on... but the build process is long ...
