### ISSUE TITLE
incorrectly have the gnome3 PPA

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix-iso-builder#6]
https://github.com/budgie-remix/budgie-remix-iso-builder/tree/master/etc/config/archives

we should only have the budgie PPA - not the gnome3 PPA because we have no control over that PPA - it could be deleted at any time.

This needs to be removed

**Comment by spottech** [comment]
Maybe re-add gnome3 ppa or build yourself the gnome 3.18 env for best match to solus os
