### ISSUE TITLE
elementary and our language lists are different

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix-iso-builder#7]
any thoughts why our two language lists are different?

http://bazaar.launchpad.net/~elementary-os/elementaryos/trunk/view/head:/etc/config/package-lists/languages.list.chroot

**Comment by spottech** [comment]
It's for reduce size of iso

**Comment by fossfreedom** [comment]
ok - I'll do a test with the elementary language lists to see how large the iso becomes.

Can I ask @spottech  - what does the languages added to this .chroot list actually do?  Are they for ubiquity or something else?

**Comment by spottech** [comment]
It's the preinstalled langages

**Comment by fossfreedom** [comment]
What are the preinstalled languages for?  Picking spanish from ubiquity already does ubiquity in spanish.

Or are these for after the installation has occurred - so "spanish" would be the language displayed?

**Comment by spottech** [comment]
I don't know for ubiquity but for the rest of desktop... Gnome and base language

**Comment by spottech** [comment]
all languages, iso size + 200Mb

**Comment by fossfreedom** [comment]
reduced to a core - english, spanish, french, german.  With locales-all fixing the installation of any locale, no longer an issue (for yakkety)
