### ISSUE TITLE
non efi live boot displays purple Ubuntu splash screen

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix-iso-builder#8]
I noticed that on boot of the live ISO the standard Ubuntu purple screen is displayed - if you press Escape it shows the normal ubuntu "try ubuntu", "install ubuntu" options with a title of Ubuntu 16.04 LTS

Is there anything we can do to "budgie-remix" this screen?

**Comment by spottech** [comment]
Hexcube work on new syslinux theme
